name: Build multi-arch image and deploy
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
  
jobs:
  build_arlfail:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      # Check out code
      - name: Checkout
        uses: actions/checkout@v2

      - id: foo
        uses: actions/docker-streama@v1
        #with:
        #  who-to-greet: 'Mona the Octocat'